info:
  contact: {}
  title: L3 API
  version: "1.0"
paths:
  /status:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Application healthcheck
      tags:
      - status
swagger: "2.0"
